### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/baseline-algorithms#2]
```
Installed c:\users\stefan\git-repos\work\swc\baseline-algorithms\src
Processing dependencies for baseline-algorithms==1.0.0
Searching for coord-interface
Reading https://pypi.org/simple/coord-interface/
Couldn't find index page for 'coord-interface' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
...
```

Looking for `coord-interface` dependency, which doesn't exist (after installing `common-utils`).
Still needs to update to the new common-utils dependency?

**Comment by adnan904** [comment]
@stefanbschneider I have already updated the dependencies of all repos. Maybe you have the old `coorination-simulation` repo. Have you pulled the latest code? 
Can you let me know how and when you are getting this error?

**Comment by stefanbschneider** [comment]
Hm, it works now. No idea what the problem was. Thanks anywas
